### Normal user login
POST http://localhost:8080/login HTTP/1.1
Accept: */*
Content-Type: application/x-www-form-urlencoded

username=user&password=password

### Normal admin login
POST http://localhost:8080/login HTTP/1.1
Accept: */*
Content-Type: application/x-www-form-urlencoded

username=admin&password=password

###
GET http://localhost:8080/informacionConductor/-1/buses
###
GET http://localhost:8080/informacionRuta/-1

###
GET http://localhost:8080/informacionBus/-2/conductores

###
PUT http://localhost:8080/agregarBus/-2/-2
Content-Type: application/json

{
    "dia": "Miercoles"
}


###
POST http://localhost:8080/logout HTTP/1.1
Accept: */*